const mongoose=require("mongoose");

const PatientSchema=new mongoose.Schema({
    First_Name:{
        type:String,
        required:true,
        trim:true,
        minlength:3,
        maxlength:200,
    },
    Last_Name:{
        type:String,
        required:true,
        trim:true,
        minlength:3,
        maxlength:200,
    },
    Gender:{
        type:String,
        required:true,
        trim:true,
        minlength:4,
        maxlength:6,
    },
    Age:{
        type:String,
        required:true,
        trim:true,
        maxlength:200,
    },
    Surgeon:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"usermodel"
    },
    Risk_Factors_And_Life_Style:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Family_History:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Neurological_Examination:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Symptoms:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Treatment_History:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Allergies:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Duration_And_Progression_Of_Symptoms:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Diagnosis:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Medical_History:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Notes:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Biopsy_Or_Pathology_Results:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Lab_Test_Result:{
        type:String,
        trim:true,
        maxlength:1000,
    },
    Current_Medications:{
        type:String,
        trim:true,
        maxlength:1000,
    }
},{
    timestamps:true
});

const Patient=mongoose.model("Patient",PatientSchema);

module.exports={
    Patient
}